### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [kevelmun/ISII-WORKSHOPS-RADIO_FOREVER#7]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by kevelmun** [comment]
The issue was analized and accepeted for the support team. We will proceed to solve it.

**Comment by kevelmun** [comment]
We will proceed to process the request, @lnsalaza will be the assigned analyst, @Joan-Gutierrez11 will develop the solution, and
@lnsalaza will perform the tests

**Comment by lnsalaza** [comment]
Good afternoon @pmaldonado-espol, the impact analysis of the issue has been made and it is attached below. The team is waiting for your revision to continue.
[Impact Analysis of the Issue.docx](https://github.com/kevelmun/ISII-WORKSHOPS-RADIO_FOREVER/files/10452058/Impact.Analysis.of.the.Issue.docx)

**Comment by pmaldonado-espol** [comment]
> Good afternoon @pmaldonado-espol, the impact analysis of the issue has been made and it is attached below. The team is waiting for your revision to continue.
> [Impact Analysis of the Issue.docx](https://github.com/kevelmun/ISII-WORKSHOPS-RADIO_FOREVER/files/10452058/Impact.Analysis.of.the.Issue.docx)

It’s Okay, but i’m not agree that a 60 minutes activity should be considered as a “mid effort”.

**Comment by Joan-Gutierrez11** [comment]
The changes in the code were made.
https://github.com/kevelmun/ISII-WORKSHOPS-RADIO_FOREVER/blob/2168fe681b16e9cd71bc7dd114710f444cb06acb/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L77-L95

**Comment by lnsalaza** [comment]
@pmaldonado-espol, Below I attach the test plan followed during the testing of the solution. Please review this file and let us now if you agree with this test plan.
[TestPlan-Issue1.pdf](https://github.com/kevelmun/ISII-WORKSHOPS-RADIO_FOREVER/files/10461513/TestPlan-Issue1.pdf)

**Comment by kevelmun** [comment]
Dear @pmaldonado-espol the solucion for the issue was made it. @Joan-Gutierrez11 will now create the new version of the software.

**Comment by Joan-Gutierrez11** [comment]
Dear @pmaldonado-espol. The new version of the software will be released, the download link is: https://github.com/kevelmun/ISII-WORKSHOPS-RADIO_FOREVER

There were no major changes in the application.

Instructions for using the program:
The program will show you first indicate the age of the client
Then he asks the customer's sex: M (for male), F (for female)
Then he is asked if he is married (Y) or not (N).
Finally, it asks if you have a valid license (Y) or not (N)
Once the data is entered, it returns the value of the insurance premium or -1 if a premium cannot be sold
Once this is finished, you will be asked if you want to enter data for the new customer.

**Comment by kevelmun** [comment]
As the solution was accepted, I will proceed to close the issue, thanks everyone.
